services:
  rsshub: # two ways to enable puppeteer:
    # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
    # * (consumes more disk space and memory) leave everything unchanged
    #        image: diygod/rsshub
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://redis:6379/"
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000" # marked
      REMOTE_CONFIG: "http://rnacos:8848/nacos/v1/cs/configs?dataId=rsshub"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1200/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
      - browserless # marked
      - rnacos

  browserless: # marked
    image: browserless/chrome # marked
    restart: always # marked
    ulimits: # marked
      core: # marked
        hard: 0 # marked
        soft: 0 # marked
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/pressure" ]
      interval: 30s
      timeout: 10s
      retries: 1

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  unhealthy_container_restart:
    image: docker:cli
    cap_drop:
      - ALL
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 60; docker ps -q -f health=unhealthy | xargs --no-run-if-empty docker restart; done" ]
    restart: unless-stopped

  rnacos:
    image: qingpan/rnacos:stable-alpine
    restart: unless-stopped
    volumes:
      - ./rnacos/io:/io:rw
      - ./rnacos/localtime:/etc/localtime:ro
    ports:
      - "10848:10848"
volumes:
  redis-data:
