name: ALL for myself

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'cnki'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: '${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_TAGS }}:latest'
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with: # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: 'op://dev/ycymakxkz7xzovg6arjqzldocq/private key'

      - name: deployment
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.MY_HOST }}
          username: root
          key: ${{ env.SECRET }}
          script: |
            cd ~/docker/rsshub
            docker compose pull
            docker compose up -d
